import './globals.css'
import App from './App'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <App children={children} />
  )
}
